name: Build

on:
  push:
    branches: ["main"]
    paths-ignore:
      - 'README.md'
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    name: Build & Package
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Check out
        uses: actions/checkout@v6.0.2
        with:
          submodules: 'recursive'
          fetch-depth: 0

      - name: Set up JDK 21
        uses: actions/setup-java@v5.2.0
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'gradle'

      - name: ccache
        uses: hendrikmuhs/ccache-action@v1.2
        with:
          key: ${{ runner.os }}-${{ github.sha }}
          restore-keys: ${{ runner.os }}

      - name: Build with Gradle
        run: |
          ccache -o cache_dir=${{ github.workspace }}/.ccache
          ccache -o hash_dir=false
          ccache -o compiler_check='%compiler% -dumpmachine; %compiler% -dumpversion'
          ccache -p
          echo 'android.native.buildOutput=verbose' >> gradle.properties
          ./gradlew :Redirector:assembleDebug :Redirector:assembleRelease :Redirector:publishToMavenLocal
        env:
          ORG_GRADLE_PROJECT_signingKey:      ${{ secrets.maven_pgp_signingKey }}
          ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.maven_pgp_signingPassword }}

      - name: Upload AAR Artifacts
        uses: actions/upload-artifact@v7.0.1
        with:
          name: ${{ matrix.os }}-binaries
          path: Redirector/build/outputs/aar/
          if-no-files-found: error
